#!/bin/bash

#todo
##.bashbeans settings (global ~/. and per project)
###folders, classpath/ext, platform info, compilers, etc.,
##support for java and clojure
###put compiler scripts into global ~/.
###javac + compiler jars vs. scalac,clojurec,...
###pass names without .ext, and let it figure it out?
##save last few hashes and mock me if I tried the exact same thing already :D
###also "compile by lookup"
#toimprove
#search .bashbeanshash and shift out already compiled, instead of doing a pure compare

starttime="$(date +%s)"
cd src

#get arguments, process switches
if [ $# -gt 0 ]; then
    for i do
        case "$i" in #dont take the strings seriously - they're used as booleans ;)
            "-f") Force="m*a";shift;;
            "-r") Run="yes please";shift;;
            "-R") Run="yes please";Unforce="<- means don't compile";shift;;
        esac
    done
    files="$@"
fi
if [ "$files" == "" ]; then
    files="  *.scala" 
fi

#bashbeans stuff
bashbeanshashpath="../.bashbeanhash"

#hash func
##@getpath za $1?
fileshash="`md5sum ../$0 $files`" #must be compiled with same bashbeans script
#echo "$fileshash"

#build
if [ "$Unforce" != "" ]; then
    echo "You told me not to compile."
    builderror="0"
elif [ "$Force" == "" -a -e $bashbeanshashpath -a "$fileshash" == "`cat $bashbeanshashpath`" ]; then
    echo "I don't think I need to compile. (use force if neccesary.)"
    builderror="0"
else
    echo "Compiling:"$files
    #fast scala compile (loads compile deamon)
    fsc -deprecation -d ../class -extdirs ../lib/lwjgl-2.7.1/jar/ $files
    
    builderror=$?
    #write hashes
    if [ "$builderror" == "0" ]; then
        echo "$fileshash" > $bashbeanshashpath
    fi
fi
buildtime="$(date +%s)"
elapsedtime="$(expr $buildtime - $starttime)"
echo "Done("$builderror") in ${elapsedtime}s."

#run it
if [ "$builderror" == "0" -a "$Run" != "" ]; then
    cd ..
    #CP="lib/lwjgl-2.7.1/jar/lwjgl.jar:lib/lwjgl-2.7.1/jar/lwjgl_util.jar:class"
    #cd $CD"class"
    scala -cp lib/lwjgl-2.7.1/jar/lwjgl.jar:lib/lwjgl-2.7.1/jar/lwjgl_util.jar:class -Djava.library.path="lib/lwjgl-2.7.1/native/linux/" AngryPigs
fi
