#!/bin/bash

#todo
##.bashbeans settings (global ~/. and per project)
###folders, classpath/ext, platform info, compilers, etc.,
##support for java and clojure
###put compiler scripts into global ~/.
###javac + compiler jars vs. scalac,clojurec,...
###pass names without .ext, and let it figure it out?
#toimprove
#search .bashbeanshash and shift out already compiled, instead of doing a pure compare

cd src

#get arguments, process switches
if [ $# -gt 0 ]; then
    for i do
        case "$i" in 
            "-f") Force="m*a";shift;;
            "-r") Run="yes please";shift;;
            "-R") Run="yes please";Unforce="don't compile :)";shift;;
        esac
    done
    C="$@"
fi
if [ "$C" == "" ]; then
    C="  *.scala" 
fi

#compile
if [ "$Unforce" != "" ]; then
    echo "you told me not to compile."
    E="0"
elif [ "$Force" == "" -a -e .bashbeanhash -a "`md5sum $C`" == "`cat .bashbeanhash`" ]; then
    echo "I don't think I need to compile. (use force if neccesary.)"
    E="0"
else
    echo "compiling:"$C
    scalac -deprecation -d ../class -extdirs ../lib/lwjgl-2.7.1/jar/ $C
    E=$?
    if [ "$E" == "0" ]; then
        md5sum $C > .bashbeanhash
    fi
fi
echo "build done("$E")."

#run it
if [ "$E" == "0" -a "$Run" != "" ]; then
    cd ..
    CP="lib/lwjgl-2.7.1/jar/lwjgl.jar:lib/lwjgl-2.7.1/jar/lwjgl_util.jar:class"
    #cd $CD"class"
    scala -cp $CP -Djava.library.path="lib/lwjgl-2.7.1/native/linux/" ShowPigs
fi
