#!/bin/bash
#todo save file times into file and only compile changed

if [ $# -gt 0 ]; then
    C=""
    for ARG in $*
    do
        C=$C" "$ARG.scala
    done
else
    C="  *.scala"
fi

echo "compiling:"$C
scalac -extdirs lib/lwjgl-2.7.1/jar/ $C

